config/routes.rb
Rails.application.routes.draw do
  resources :bands

  root "bands#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/band.rb
class Band < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: %i[ show edit update destroy ]

  # GET /bands or /bands.json
  def index
    if params[:query].present?
      @bands = Band.where("name LIKE ?", "%#{params[:query]}%")
    else
      @bands = Band.all
    end

    if turbo_frame_request?
      render partial: "bands", locals: { bands: @bands }
    else
      render :index
    end
  end

  # GET /bands/1 or /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands or /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to band_url(@band), notice: "Band was successfully created." }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1 or /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to band_url(@band), notice: "Band was successfully updated." }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1 or /bands/1.json
  def destroy
    @band.destroy

    respond_to do |format|
      format.html { redirect_to bands_url, notice: "Band was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def band_params
      params.require(:band).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_band.html.erb
<div id="<%= dom_id band %>">
  <p class="text-lg leading-loose">
    <%= link_to band.name, band_path(band), class: "text-orange-600 underline hover:text-orange-700" %>
  </p>
</div>

app/views/bands/_bands.html.erb
<%= turbo_frame_tag "bands" do %>
  <%= render bands %>
<% end %>

app/views/bands/_form.html.erb
<%= form_with(model: band) do |form| %>
  <% if band.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
        <% band.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing band</h1>

<%= render "form", band: @band %>

<br>

<div>
  <%= link_to "Show this band", @band %> |
  <%= link_to "Back to bands", bands_path %>
</div>

app/views/bands/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="font-bold text-3xl mb-3">Bands</h1>

<%= form_with(url: bands_path, method: :get, data: {controller: "search-form", turbo_frame: "bands", turbo_action: "advance"}) do |form| %>
  <%= form.label :query, "Search by band name:", class: "block mb-2" %>
  <div class="flex space-x-3">
    <%= form.text_field :query, class: "py-3 px-4 rounded border ring-0 focus:ring-4 focus:ring-orange-100 focus:shadow-none focus:border-orange-500 focus:outline-none", data: {action: "input->search-form#search"} %>

    <%= form.submit 'Search', class: "px-4 py-3 font-medium bg-orange-300 text-neutal-900 rounded flex items-center cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0 focus:ring-orange-100" %>
  </div>
<% end %>

<div class="my-6">
  <%= render "bands", bands: @bands %>
</div>

<%= link_to "New band", new_band_path, class: "px-4 py-3 font-medium bg-orange-300 text-neutal-900 rounded inline-flex items-center cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0 focus:ring-orange-100" %>

app/views/bands/new.html.erb
<h1>New band</h1>

<%= render "form", band: @band %>

<br>

<div>
  <%= link_to "Back to bands", bands_path %>
</div>

app/views/bands/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @band %>

<div>
  <%= link_to "Edit this band", edit_band_path(@band) %> |
  <%= link_to "Back to bands", bands_path %>

  <%= button_to "Destroy this band", @band, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboChargedSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container mx-auto my-16 lg:px-10 px-4">
      <%= yield %>
    </div>
  </body>
</html>